workflows:
  safebuds-android:
    name: Safebuds Android CI/CD
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - keystore_credentials
        - firebase_credentials
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Apply Firebase config
        script: |
          cp "$ANDROID_GOOGLE_SERVICES_JSON" android/app/google-services.json
          echo "✅ Firebase config copied"
      - name: Prepare Android signing
        script: |
          cat > android/key.properties <<EOF
          storePassword=$STORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=$ANDROID_KEYSTORE
          EOF
          echo "✅ key.properties generated"
      - name: Build APK
        script: flutter build apk --release
      - name: Build AppBundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
